# Generated by Django 4.2.6 on 2023-10-10 18:53

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='queue',
            field=models.JSONField(default=search.models.queue),
        ),
    ]
