# Generated by Django 4.2.5 on 2023-10-07 12:08

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=9)),
                ('work_schedule', models.JSONField(default=search.models.shedule)),
                ('services', models.JSONField(default=search.models.mock_services)),
            ],
        ),
    ]
