# Generated by Django 4.2.5 on 2023-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
