# Generated by Django 4.2.5 on 2023-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_bank_latitude_alter_bank_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='latitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bank',
            name='longitude',
            field=models.CharField(max_length=25),
        ),
    ]
